language: objective-c
osx_image: xcode9.2
skip_cleanup: true
env:
  global:
  - FRAMEWORK_NAME=PopcornKit
before_deploy:
- carthage build --no-skip-current
- carthage archive $FRAMEWORK_NAME
deploy:
  provider: releases
  api_key:
    secure: dPdPVqtbkQedHUqE84IwR4LGhL+eMwAVAjUC9CPm83t8+OTftWooJs7so4w64dLzHSlqGEr66uFT0bCUp1YB8AFJsyvzn3YAGdD0FSAThDn/JoQTjpD732nhyAXCTXEmqq59nRmYCM87ZZu/SADwjr44HbPOKRF+Y+VYqKmSqUKs9NN8lBHCvLN24f9OsAQADKBwOsAeyN5Z7hCVxRXGuyuf2Nz2MMSe5TljVkxAYsPwRanJ63cqkveEF0Rc+6NXmdE3/qb/aLy+qH85SjNEFE12Hl/yhJrk7dunnhL40psybQfERKzvCxAZCWLVKl0E9FLLT0UYwGAiDafhQNKJ4AYTNhM0EwJvi/Hc98GZOXQSq7ujJz43mNlmv7uiFUzpTnKk0yWRWDeKL1DsmFTJVqU6/N68QEJJ5ft7xRa9DmxN2I4vX3F5ppFi73TKPFQiQQ1ADYu4j03jrVaSX12NT/fC9cbi6DL9IM/vSkMPO0v89JIUhT7hFO75p9Vdvtf8x3+Se6rBmM/LKzFyz80WitfXnFosDKKZwDhOJyWPm0c+G7svFYMgszq303prtHZXW2DfPAdqEyIhhtevdZUjthfttfgOaRikz6PKtuWZpP66sMqwPnE1pgaj4tjV/LJNZeZqksIPXQjGAA4+sEeZapcbYt+9R/lot45x357ycgU=
  file: $FRAMEWORK_NAME.framework.zip
  on:
    repo: mourke/PopcornKit
notifications:
  email: false
